### ISSUE TITLE
直接fork过去都失败

### ISSUE THREAD

**Issue by 3136083906** [jingleijack/AX6-AX3600_Almighty-Edition_Config#8]
fork过去没做任何修改都运行失败，更别提修
![9E756BC5-107D-4D4D-ABF1-C6847006085B](https://user-images.githubusercontent.com/30095132/147871450-d67ad336-de5a-4324-ba10-0f5fa24d4219.png)
改了，我也不知道为什么

**Comment by EYW-015** [comment]
我也是，直接照搬过去也失败，人都懵的
